### ISSUE TITLE
Missing Licence

### ISSUE THREAD

**Issue by netpipe** [espmaniac/midi_file_parser#1]
please add a licence

**Comment by netpipe** [comment]
any reason you chose GPL i dont really know much about it because its the only restrictive licence. maybe we could get this as LGPL then its less wondering for programmers to use.

https://github.com/netpipe/Luna had plans on using it inside the source tree here. but most of the engine is apache/irrlicht or mit licence

**Comment by netpipe** [comment]
on second thought it should work great i just need to get in the habbit of dating my code changes and marking them down.

**Comment by espmaniac** [comment]
To be honest, I don't understand anything about licenses. I just want to write code and share it. If you want to take my code then just take it.

**Comment by espmaniac** [comment]
I don't see much difference between GPL and LGPL licenses. The main difference between the GPL and the LGPL is that the latter allows the work to be linked with (in the case of a library, "used by") a non-(L)GPLed program, regardless of whether it is licensed under a license of GPL family or other licenses.

**Comment by espmaniac** [comment]
If you want me to change my license, then tell me which one to take.

**Comment by netpipe** [comment]
ZLib is best licence because you dont need to mention it in the documentation

"ZLib is more liberal then MIT license, because Zlib doesn't require a mention of library usage in the documentation. MIT requires a mention in the documentation ('this project uses'). Some publishers don't like this. In practice, GPL & LGPL CANNOT be used in commercial game projects on consoles for free."

**Comment by espmaniac** [comment]
I didn't find your license in the list of templates. But I found a license called "unlicense".

**Comment by netpipe** [comment]
https://opensource.org/licenses/Zlib , basically a disclaimer from liability's and a way to get credit if someone see's your code. i really appreciate being able to use this code its going to make fluidlite sound amazing. should be ready from the freelancer in 2 or 3 days.

**Comment by espmaniac** [comment]
Let me take a unlicense, there is the same text.

**Comment by netpipe** [comment]
sounds amazing, thanks a bunch.

**Comment by netpipe** [comment]
one thing if you want to do is add your credits to the code name and github url maybe. that way they can find out where to send the changes

**Comment by espmaniac** [comment]
I don't think it's necessary.
